name: ape-borg-core
contracts_folder: out  # Use Foundry's output directory
dependencies: []  # No compilation dependencies needed
compiler:
  use_cache: false
  solc:
    version: 0.8.20  # For consistency, though not used
networks:
  base:
      provider: "http://localhost:8545"
      chain_id: 8453  # Explicitly set to match Base mainnet's chain ID