name: ape-borg-core
contracts_folder: out
dependencies: []
compiler:
  use_cache: false
  solc:
    version: 0.8.20

networks:
  base:
    local:
      uri: http://127.0.0.1:8545
      chain_id: 8453
      explorer:
        etherscan:
          api_key: "UYX48KBVIAYMM38RZJI6PAIZ8U16MZCGNK"
          uri: "https://api.basescan.org/api"

foundry:
  fork:
    base:
      local:
        block_number: 
